TRUNCATE kegiatan_patroli CASCADE;
TRUNCATE patroli_darat CASCADE;
TRUNCATE patroli_udara CASCADE;
TRUNCATE provinsi CASCADE;
TRUNCATE daops CASCADE;
TRUNCATE kota_kab CASCADE;
TRUNCATE kecamatan CASCADE;
TRUNCATE desa_kelurahan CASCADE;